FROM orbbec_ros:noetic
ENV TZ=ET
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y upgrade

COPY ./vibro_tactile_toolbox /ros1_ws/src/vibro_tactile_toolbox

RUN cd /ros1_ws/src/vibro_tactile_toolbox \
   && pip install -r requirements.txt  

RUN source /opt/ros/noetic/setup.bash \
 && cd /ros1_ws \
 && catkin build

COPY ./vibro_tactile_toolbox/docker/vibro_tactile_entrypoint.sh /vibro_tactile_entrypoint.sh
RUN chmod +x /vibro_tactile_entrypoint.sh

ENTRYPOINT ["/vibro_tactile_entrypoint.sh"]
CMD ["bash"]
