version: "3"

services:
  realsense-and-sounddevice-ros:
    image: "noetic_realsense_and_sounddevice_ros:latest"
    container_name: "noetic_realsense_and_sounddevice_ros_container"
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /dev:/dev
    privileged: true
    network_mode: "host"
    ipc: "host"
    restart: "unless-stopped"
    command: bash -c "source /ros1_ws/devel/setup.bash && roslaunch vibro_tactile_toolbox realsense_and_sounddevice.launch"

  orbbec-ros:
    image: "noetic_orbbec_ros:latest"
    container_name: "noetic_orbbec_ros_container"
    environment:
      - "DISPLAY=unix${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /dev:/dev
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    restart: "unless-stopped"
    command: bash -c "source /opt/ros/noetic/setup.bash && source /ros1_ws/devel/setup.bash && roslaunch vibro_tactile_toolbox orbbec.launch"
