FROM nvidia_ros:noetic
ENV TZ=ET
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y upgrade

# Clone detectron2
RUN cd /Documents \
    && git clone https://github.com/facebookresearch/detectron2.git \
    && cd detectron2 \
    && pip install -e .

# Clone Segment Anything 
RUN cd /Documents \
    && git clone https://github.com/facebookresearch/segment-anything.git \
    && cd segment-anything \
    && pip install onnx scikit-image onnxruntime-gpu simplification distinctipy scikit-learn

# Clone Segment Anything Labeling Tool
RUN cd /Documents \
    && git clone https://github.com/cmu-mfi/salt.git \
    && cp salt/helpers/* segment-anything/

# Clone vibro_tactile_toolbox repo
RUN cd /ros1_ws/src \
    && git clone https://github.com/cmu-mfi/vibro_tactile_toolbox.git \
    && cd vibro_tactile_toolbox \
    && pip install -r requirements.txt

# Audio (https://github.com/firephinx/sounddevice_ros)
RUN cd /ros1_ws/src \ 
    && git clone https://github.com/firephinx/sounddevice_ros.git

RUN source /opt/ros/noetic/setup.bash \
 && cd /ros1_ws \
 && catkin build

# Add sourcing to bashrc
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /vibro_tactile_toolbox/ros1_ws/install/setup.bash" >> ~/.bashrc

RUN echo "All Done "