FROM nvidia_ros:noetic
ENV TZ=ET
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y upgrade

# Clone detectron2
RUN cd /Documents \
    && git clone https://github.com/facebookresearch/detectron2.git \
    && cd detectron2 \
    && pip install -e .

# Clone Segment Anything 
RUN cd /Documents \
    && git clone https://github.com/facebookresearch/segment-anything.git \
    && cd segment-anything \
    && pip install onnx scikit-image onnxruntime-gpu simplification distinctipy scikit-learn

# Clone Segment Anything Labeling Tool
RUN cd /Documents \
    && git clone https://github.com/cmu-mfi/salt.git \
    && cp salt/helpers/* segment-anything/

# Audio (https://github.com/firephinx/sounddevice_ros)
RUN cd /ros1_ws/src \ 
    && git clone https://github.com/firephinx/sounddevice_ros.git \
    && apt-get install libportaudio2 libasound-dev \
    && pip install librosa sounddevice pysoundfile

# Clone the yk_msgs repo
RUN cd /ros1_ws/src \
    && git clone https://github.com/cmu-mfi/motoman_ros1.git \
    && cd motoman_ros1 \
    && rm -rf testbed_utils \
    && rm -rf lego_moveit \
    && rm -rf motoman_gp4_moveit_config \
    && rm -rf depend-packages \
    && rm -rf yk_tasks

# Clone the robotiq_mm_ros repo
RUN cd /ros1_ws/src \
    && git clone https://github.com/cmu-mfi/robotiq_mm_ros.git

RUN source /opt/ros/noetic/setup.bash \
 && cd /ros1_ws \
 && catkin build -c

