FROM ros_desktop_full:noetic
ENV TZ=ET
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y upgrade

# Audio (https://github.com/firephinx/sounddevice_ros)
RUN cd /ros1_ws/src \ 
    && git clone https://github.com/firephinx/sounddevice_ros.git \
    && apt-get install libportaudio2 libasound-dev \
    && pip install sounddevice pysoundfile 

RUN source /opt/ros/noetic/setup.bash \
 && cd /ros1_ws \
 && catkin build

