version: "3"

services:
  robotiq-mm-ros:
    build:
      context: .
      dockerfile: Dockerfile.robotiq_mm_ros
    image: "robotiq_mm_ros:noetic"
    container_name: "robotiq_mm_ros_noetic"
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "NAMESPACE=${NAMESPACE}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /dev:/dev
    privileged: true
    network_mode: "host"
    ipc: "host"
    restart: "unless-stopped"
    command: bash -c "source /ros1_ws/devel/setup.bash && roslaunch robotiq_mm_ros robotiq_server.launch namespace:=${NAMESPACE}"
  
  sounddevice-ros:
    build:
      context: .
      dockerfile: Dockerfile.sounddevice_ros
    image: "sounddevice_ros:noetic"
    container_name: "sounddevice_ros_noetic"
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "NAMESPACE=${NAMESPACE}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /dev:/dev
    privileged: true
    network_mode: "host"
    ipc: "host"
    restart: "unless-stopped"
    command: bash -c "source /ros1_ws/devel/setup.bash && roslaunch vibro_tactile_toolbox sounddevice.launch namespace:=${NAMESPACE}"

  realsense-ros:
    build:
      context: .
      dockerfile: Dockerfile.realsense_ros
    image: "realsense_ros:noetic"
    container_name: "realsense_ros_noetic"
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "NAMESPACE=${NAMESPACE}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /dev:/dev
    privileged: true
    network_mode: "host"
    ipc: "host"
    restart: "unless-stopped"
    command: bash -c "source /ros1_ws/devel/setup.bash && roslaunch vibro_tactile_toolbox realsense.launch namespace:=${NAMESPACE}"

  orbbec-ros:
    build:
      context: .
      dockerfile: Dockerfile.orbbec_ros
    image: "orbbec_ros:noetic"
    container_name: "orbbec_ros_noetic"
    environment:
      - "DISPLAY=unix${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "NAMESPACE=${NAMESPACE}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /dev:/dev
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    restart: "unless-stopped"
    command: bash -c "source /opt/ros/noetic/setup.bash && source /ros1_ws/devel/setup.bash && roslaunch vibro_tactile_toolbox orbbec.launch namespace:=${NAMESPACE}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vibro-tactile-toolbox:
    build:
      context: .
      dockerfile: Dockerfile.vibro-tactile_toolbox
    image: "vibro_tactile_toolbox:noetic"
    container_name: "vibro_tactile_toolbox_noetic"
    environment:
      - "DISPLAY=unix${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "NAMESPACE=${NAMESPACE}"
      - "TYPE=${TYPE}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /dev:/dev
      - ${HOME}/:/home
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    restart: "unless-stopped"
    command: bash -c "source /opt/ros/noetic/setup.bash && source /ros1_ws/devel/setup.bash && roslaunch vibro_tactile_toolbox vibro_tactile_toolbox.launch namespace:=${NAMESPACE} type:=${TYPE}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
