lego_ee_tf: "lego_ee.tf"
lego_world_tf: "T_lego_world/"
tmp_lego_world_tf: "tmp_lego_world.tf"
data_dir: "/mnt/hdd1/vibrotactile_data/lego/"
model_dir: "/models/"
transforms_dir: "/transforms/"
x_range:
  - -0.005
  - 0.005
y_range: 
  - -0.005
  - 0.005
theta_range: 
  - -10.0
  - 10.0
block_x_range: 
  - -12
  - -2
block_y_range:
  - 4
  - 13
skill_params:
  pull_up:
    lift_height_offset: 0.01
    velocity_scaling: 0.001
    force_threshold: 2.0
  place_lego:
    place_rotation: 15
    lift_height_offset: 0.04
  pick_lego:
    pick_rotation: 15
    lift_height_offset: 0.04
  move_to_above_perturb_pose:
    approach_height_offset: 0.04
  move_to_above_correct_pose:
    approach_height_offset: 0.04
  move_down:
    height_offset: 0.04
audio_detector:
  namespace: namespace
  topic_name: '/namespace/audio'
fts_detector:
  namespace: namespace
  topic_name: '/namespace/fts'
  force_threshold: 0.3
lego_detector:
  namespace: namespace
  topic_name: '/namespace/side_camera/color/image_cropped/compressed'
  top_bbox:
    - 500
    - 280
    - 1200
    - 430
  bot_bbox:
    - 500
    - 400
    - 1200
    - 600
  detection_threshold: 0.8
rosbag_data_recorder:
  topics:
    - /namespace/side_camera/color/image_cropped/compressed
    - /namespace/wrist_camera/color/image_raw/compressed
    - /namespace/joint_states
    - /namespace/fts
    - /namespace/audio
    - /namespace/audio_info
    - /namespace/terminator/skill_termination_signal
    - /namespace/terminator/audio_termination_signal
    - /namespace/terminator/fts_termination_signal
    - /namespace/outcome/audio_detector
    - /namespace/outcome/audio_detector/spectrogram
    - /namespace/outcome/lego_detector
    - /namespace/outcome/fts_detector
    - /namespace/skill/param
    - /namespace/terminator/termination_config