
waterproof_world_pick_tf: "/transforms/waterproof_world_pick.tf"
waterproof_world_place_tf: "/transforms/waterproof_world_place.tf"
waterproof_world_place_reset_tf: "/transforms/waterproof_world_place_reset.tf"
waterproof_world_reset_x_tf: "/transforms/waterproof_world_reset_x.tf"
waterproof_world_reset_y_tf: "/transforms/waterproof_world_reset_y.tf"
dsub_world_pick_tf: "/transforms/dsub_world_pick.tf"
dsub_world_place_tf: "/transforms/dsub_world_place.tf"
dsub_world_place_reset_tf: "/transforms/dsub_world_place_reset.tf"
dsub_world_reset_x_tf: "/transforms/dsub_world_reset_x.tf"
dsub_world_reset_y_tf: "/transforms/dsub_world_reset_y.tf"
transforms_dir: "/transforms/"
hande_ee_tf: "hande_ee.tf"
data_dir: "/mnt/hdd1/vibrotactile_data/nist/"
x_range:
  - -0.005
  - 0.005
y_range: 
  - -0.005
  - 0.005
theta_range: 
  - -10.0
  - 10.0
pick_approach_height: 0.08
place_approach_height: 0.03
reset_x_offset: 0.008
reset_y_offset: 0.01
lift_height: 0.01
pull_up_velocity_scaling: 0.01
dsub_push_down_height_offset: 0.01
waterproof_push_down_height_offset: 0.02
velocity_scaling_large_movements: 0.5
audio_detector:
  namespace: namespace
  topic_name: '/namespace/audio'
  dsub_model_path: '/home/mfi/repos/ros1_ws/src/kevin/vibro_tactile_toolbox/models/audio_outcome_dsub.pt'
  waterproof_model_path: '/home/mfi/repos/ros1_ws/src/kevin/vibro_tactile_toolbox/models/audio_outcome_waterproof.pt'
fts_detector:
  namespace: namespace
  topic_name: '/namespace/fts'
  force_threshold: 10.0
rosbag_data_recorder:
  topics:
    - /namespace/side_camera/color/image_cropped/compressed
    - /namespace/wrist_camera/color/image_raw/compressed
    - /namespace/joint_states
    - /namespace/fts
    - /namespace/audio
    - /namespace/audio_info
    - /namespace/terminator/skill_termination_signal
    - /namespace/outcome/audio_detector
    - /namespace/outcome/fts_detector
    - /namespace/skill/param
    - /namespace/terminator/termination_config