hande_ee_tf: "/transforms/hande_ee.tf"
waterproof_world_pick_tf: "/transforms/waterproof_world_pick.tf"
waterproof_world_place_tf: "/transforms/waterproof_world_place.tf"
waterproof_world_place_reset_tf: "/transforms/waterproof_world_place_reset.tf"
waterproof_world_reset_x_tf: "/transforms/waterproof_world_reset_x.tf"
waterproof_world_reset_y_tf: "/transforms/waterproof_world_reset_y.tf"
dsub_world_pick_tf: "/transforms/dsub_world_pick.tf"
dsub_world_place_tf: "/transforms/dsub_world_place.tf"
dsub_world_reset_x_tf: "/transforms/dsub_world_reset_x.tf"
dsub_world_reset_y_tf: "/transforms/dsub_world_reset_y.tf"
data_dir: "/mnt/hdd1/vibrotactile_data/nist/"
x_range:
  - -0.005
  - 0.005
y_range: 
  - -0.005
  - 0.005
theta_range: 
  - -10.0
  - 10.0
approach_height: 0.08
reset_x_offset: 0.008
reset_y_offset: 0.01
lift_height: 0.01
pull_up_velocity_scaling: 0.01
fts_detector:
  namespace: namespace
  topic_name: '/namespace/fts'
  force_threshold: 10.0
rosbag_data_recorder:
  topics:
    - /namespace/side_camera/color/image_cropped/compressed
    - /namespace/wrist_camera/color/image_raw/compressed
    - /namespace/joint_states
    - /namespace/fts
    - /namespace/audio
    - /namespace/audio_info
    - /namespace/terminator/skill_termination_signal
    - /namespace/outcome/fts_detector
    - /namespace/skill/param
    - /namespace/terminator/termination_config