transforms_dir: "/transforms/"
hande_ee_tf: "hande_ee.tf"
data_dir: "/mnt/hdd1/vibrotactile_data/nist/"
model_dir: "/models/"
x_range:
  - -0.005
  - 0.005
y_range: 
  - -0.005
  - 0.005
theta_range: 
  - -10.0
  - 10.0
pick_approach_height: 0.08
place_approach_height: 0.03
reset_x_offset: 0.008
reset_y_offset: 0.01
lift_height: 0.01
pull_up_velocity_scaling: 0.01
pull_up_force_threshold: 8.0
push_down_height_offset: 0.01
velocity_scaling_large_movements: 1.0
audio_detector:
  namespace: namespace
  topic_name: '/namespace/audio'
fts_detector:
  namespace: namespace
  topic_name: '/namespace/fts'
  force_threshold: 12.0
rosbag_data_recorder:
  topics:
    - /namespace/side_camera/color/image_cropped/compressed
    - /namespace/wrist_camera/color/image_raw/compressed
    - /namespace/joint_states
    - /namespace/fts
    - /namespace/audio
    - /namespace/audio_info
    - /namespace/terminator/skill_termination_signal
    - /namespace/terminator/audio_termination_signal
    - /namespace/terminator/fts_termination_signal
    - /namespace/outcome/audio_detector
    - /namespace/outcome/fts_detector
    - /namespace/skill/param
    - /namespace/terminator/termination_config