transforms_dir: "/transforms/"
hande_ee_tf: "hande_ee.tf"
data_dir: "/home/Documents/vibrotactile_data/nist"
model_dir: "/models/"
x_range:
  - -0.005
  - 0.005
y_range: 
  - -0.005
  - 0.005
theta_range: 
  - -10.0
  - 10.0
skill_params:
  place_connector_reset:
    reset_x_offset: 0.008
    approach_height_offset: 0.03
  reset_connector:
    reset_x_offset: 0.008
    reset_y_offset: 0.01
  pick_connector:
    approach_height_offset: 0.08
  place_connector:
    approach_height_offset: 0.03
  pull_up:
    lift_height_offset: 0.01
    velocity_scaling: 0.01
    force_threshold: 8.0
  push_down:
    height_offset: 0.01
  move_up:
    lift_height_offset: 0.08
  move_down:
    height_offset: 0.03
  move_to_above_perturb_pose:
    'approach_height_offset': 0.03
    'velocity_scaling': 1.0
  move_to_above_correct_pose:
    'approach_height_offset': 0.03
audio_detector:
  namespace: namespace
  topic_name: '/namespace/audio'
  channels: 
    - 0
    - 1
    - 2
    - 3
fts_detector:
  namespace: namespace
  topic_name: '/namespace/fts'
  force_threshold: 12.0
ros_services:
  - /namespace/fts_detector
  - /namespace/audio_detector
rosbag_data_recorder:
  topics:
    - /namespace/side_camera/color/image_cropped/compressed
    - /namespace/wrist_camera/color/image_raw/compressed
    - /namespace/joint_states
    - /namespace/fts
    - /namespace/audio
    - /namespace/audio_info
    - /namespace/terminator/skill_termination_signal
    - /namespace/terminator/audio_termination_signal
    - /namespace/terminator/fts_termination_signal
    - /namespace/outcome/audio_detector
    - /namespace/outcome/fts_detector
    - /namespace/skill/param
    - /namespace/terminator/termination_config